### ISSUE TITLE
Installing ROS on Fedora

### ISSUE THREAD

**Issue by danogbuagu** [realm/realm-object-server#1]
I suggest enabling installation of ROS on Fedora - at least, to aid adoption.
Please, my problem is the inability to install Realm Object Server on Fedora - I know Fedora was not listed as a compatible OS; but I thought that what is good for RHEL should be good for Fedora 24.

**Comment by teotwaki** [comment]
Hi @danogbuagu, and congrats on filing the first issue here :smile_cat:.

The main reason for focusing on RHEL and Ubuntu first is simply because those are obvious production targets. In my experience (which might be wrong), Fedora is usually more of a laptop/desktop environment than a server environment; these days anyway.

However, we'll take your suggestion under advisement. The main "blocker" is that even though compiling/packaging isn't that complicated, it still requires a fair amount of testing, and as you can imagine, we have a lot of that going on at the moment.

Just for my personal information, would a docker image lessen your problem?

**Comment by danogbuagu** [comment]
Thanks, Sebastian.
In my own part of the World, we are still learning (I mean, in a lot of
things). I might consider switching over to Ubuntu.

**Comment by bmunkholm** [comment]
Cloud is now the default for non enterprise customers.
