### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by DevAndArtist** [realm/realm-object-server#11]
Hello Realm Community,

the Realm mobile platform is now in the beta state. I've seen on stackoverflow a few threads about the client side api to manage realm permissions which is not yet implemented or made public.

[http://stackoverflow.com/a/39801679/4572536](http://stackoverflow.com/a/39801679/4572536)

I'd love to see a public roadmap on what features we can expect in the near future and what is on the current todo list for the first stable release.

**Comment by teotwaki** [comment]
Hi @DevAndArtist,

I'll try get back to you ASAP on this. I just need to check some things internally.

**Comment by DevAndArtist** [comment]
@teotwaki the reason I'm asking for the roadmap is, because I'm not sure what can I build with the developer license and what I can't. 

* How can I discover other user?
* How to I implement remote push notifications? I feel it's not possible with the developer license. 

For a new startup of ours we want to build an app where we can discover other user under specific circumstances. Exchange messages between connected user. Notify with push notifications. Etc.

**Comment by bigfish24** [comment]
Right now we can't provide a full detailed roadmap, but let me answer some of your concerns:

>How can I discover other users?

The user list currently lives in a Realm on the server called the `admin.realm`. We are exploring adding additional profile data to the `User` so that there could be a client API to lookup users in the `admin.realm`. This functionality can already be built manually with the enterprise edition using the Node.js SDK.

>How do I implement remote push notifications? I feel like it's not possible with the developer license.

This would require the enterprise edition with the Node.js SDK, but we are exploring adding this functionality directly to the server, such that a push notification can be used when a client is disconnected to wake it back up to enable background sync.

>Will I be able to sync only specific realms from the server, or does my client copy everything, even realm from other users that it can't access?

The client SDK only syncs Realms when you open a synchronized Realm. To open a synchronized Realm requires a `User` object, so a `User` can only open Realms he/she has access to. This means that the server will always contain a large number of Realms, but each app will only sync/copy the ones needed for the `User` of the app.

>I don't know yet, but I think the enterprise license is very expensive, without a start budget I don't think we can afford it now. :/

The enterprise version is geared for larger teams, but we would like to find a model that works for startups as well. We are exploring a "Pro" version that would be a middle tier of functionality. Your feedback here is extremely helpful in understanding what this might look like.

**Comment by alexbrothman** [comment]
@bigfish24 I would really appreciate a "pro" version with the functionality you're describing. I certainly don't need the full enterprise package and support for my projects but push notifs and a user discovery API are a great start. Messaging and collaboration apps are listed as examples of what can be built using the platform and this would enable non-enterprises the ability to build them.

**Comment by DiogoAndre** [comment]
> The enterprise version is geared for larger teams, but we would like to find a model that works for startups as well. We are exploring a "Pro" version that would be a middle tier of functionality. Your feedback here is extremely helpful in understanding what this might look like.

I'm with @bigfish24 here. A Pro version would be most welcome. Hosted, some kind of push notification support (which can be via a third party), user discovery and access permissions settings are the most desired features for me.

**Comment by dsjstc** [comment]
Also interested in a Pro version.  

For simplicity on your end, I'd suggest giving it full enterprise features, but finding some kind of licensing limitation that would allow Startups to use it while still requiring an Enterprise license for those who can afford it.  IE, cap the number of users, number of production servers, or something like that.

**Comment by DevAndArtist** [comment]
I just noticed the `"Pro"` version. 1500$/Month? Really?

**Comment by teotwaki** [comment]
Hi @DevAndArtist,

I understand your reaction. The Professional Edition of the Realm Object Server can easily handle tens of thousands of simultaneous end-users, which means that it's mainly targetted towards medium sized businesses. Obviously, we're still working on other price points, which might match more with what small businesses and early-stage startups expect.

Please bear in mind that the Developer Edition is 100% free of charge, and we are continuously improving the features it provides. It's not like what we have released is the end of it, and that from now on, all new features are only going to be in the Professional and Enterprise edition. For example, we recently [launched better permission handling](https://realm.io/news/realtime-collaboration-now-for-every-mobile-developer/), and that is available in all versions.

We haven't forgotten about your request for a publicly available roadmap, either ;).

**Comment by dsjstc** [comment]
@Teotwaki, any progress on the original intent of this thread: to publish a feature roadmap?  

EG, I'd really like to know how far in the future it's likely to be before there's a native java client to the MOS.  It'd be great to see it either (a) on the roadmap with a target date, or (b) not on the roadmap, so I know that if that's functionality I need, I have to bake it into the intial design.

**Comment by DevAndArtist** [comment]
@teotwaki I do understand that the mobile platform is a powerful beast when you can use it's full potential and stuff. Don't get me wrong here, as much as I like Realm, I really wish for some *human* price entries. If one day Realm is going to offer something similar like [Firebase](https://firebase.google.com/), count me in. ;)

**Comment by bigfish24** [comment]
@dsjstc at this time we can't commit to timing with regards to a native java client, but at least for this, I can say it is on our roadmap. We started with Node.js as a server-side SDK to access the synchronized Realms in ROS, but we would like to support other languages. The initial targets would be C# and Java since we can adapt our client SDKs in Xamarin and Android.

If you could create an issue for this specifically, I would be happy to update once I can provide more info.

**Comment by bigfish24** [comment]
@DevAndArtist are you interested in a cloud offering specifically? If so could you create an issue for this directly as I would like to capture feedback around this.

**Comment by tgbarker** [comment]
As it very much interests me and others I know, should there be another topic on providing more functionality than the developer edition at a "human price"?

**Comment by codegrue** [comment]
I would like a price model like Unity where it's free until your app makes a certain threshold of money then you have to buy a license. Then everyone can share in the successes we build together
