### ISSUE TITLE
he repository 'https://packagecloud.io/realm/realm/linuxmint serena Release' does not have a Release file.

### ISSUE THREAD

**Issue by YeWintNaing05** [realm/realm-object-server#270]
## Goals

Getting started with realm in linux mint 18.0
## Expected Results
Working database with realm and to see realm object server

## Actual Results
I got this error "Unable to locate package realm-object-server-developer"
and "The repository 'https://packagecloud.io/realm/realm/linuxmint serena Release' does not have a Release file."

## Steps to Reproduce

I ve followed the setup instruction of the getting started realm section for linux installation.
curl -s https://packagecloud.io/install/repositories/realm/realm/script.deb.sh | sudo bash
sudo apt-get update
sudo apt-get install realm-object-server-developer

after curl,when i do apt-get update, i got this

The repository 'https://packagecloud.io/realm/realm/linuxmint serena Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.

at this i got error
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package realm-object-server-developer

**Comment by sytolk** [comment]
related https://github.com/realm/realm-mobile-platform/issues/177

**Comment by tlhunter** [comment]
I've had this issue a few times when installing Ubuntu software on Linux Mint. The problem is that Mint reports its release name as `serena`. Most APT repositories don't know about Mint, just Ubuntu, and expect the Ubuntu equivalent, e.g. `zesty`.

I think at this point the APT source file has been created but with the wrong release name. Try editing the following file and replacing occurrences of `serena` with `zesty`:

```
/etc/apt/sources.list.d/realm_realm.list
```

Then do an `apt update` and an `apt upgrade` and see if it's any better.

**Comment by bmunkholm** [comment]
@YeWintNaing05 We made a new 2.0 release that has a new installation method, which hopefully gets's around all those platform-specific issues. Please try that instead and let us know if that solves it for you?
