### ISSUE TITLE
Feature: Studio: Select multiple rows

### ISSUE THREAD

**Issue by rubengarciam** [realm/realm-object-server#313]
## Goals

Select multiple rows and perform the same action on them (i.e, 'delete')

## Expected Results

Saving ridiculous amount of time 

## Actual Results

None, one by one

**Comment by nirinchev** [comment]
Ping @kraenhansen

**Comment by kraenhansen** [comment]
Can you think of other operations than bulk deletion that this could be useful for?

**Comment by astigsen** [comment]
Drag-n-drop

**Comment by rubengarciam** [comment]
@kraenhansen any operation on either the full items or specific properties would definitely be welcomed

**Comment by calumk** [comment]
+1 
I Cant believe this isn't implemented

Studio seems to me to be larger, (150mb bigger - but electron based and cross platform, so i understand why)
And less functional than browser was, and missing many of the features i would expect from a database editor.

**Things missing that were in browser**
Keyboard shortcuts (add new row)
Lock? 
Export CSV

**Things that are annoying**
MODALS EVERYWHERE- in browser, you could add an object (using a shortcut) and then you simply clicked the object to edit. Database applications really don't need Modals with delays and transition animations, and opacity. its just irritating. 

Why cant I edit schema in the studio? 
Ok so it might not be 100% the best way to do it, but sometimes you just _dont need_ to migrate everything, I just wanna add or delete a row, or change the datatype, If I'm in the early stage of development, Why cant i just do that in the studio?

I would really expect something like SQLiteStudio (or many other database applications)
Because this just feels so... limiting, 
<img width="935" alt="screen shot 2018-01-23 at 11 51 39" src="https://user-images.githubusercontent.com/1183991/35274398-dc276b78-0033-11e8-9f23-4a793e1022b7.png">

**Comment by rubengarciam** [comment]
(sorry, closed it by mistake)

**Comment by bigfish24** [comment]
Just a heads up, this feature is in review internally and we hope to get it released in the coming week.

@calumk appreciate the feedback and it is definitely noted on our end. In adding the create object functionality we debated the modal UI, but ultimately it was the easier to implement so our plan was to get that done and then later add the editing in line. AppKit definitely provides a lot of this out of the box compared to JS (like keyboard shortcuts too), so I apologize that it isn't as optimized right now. We would love if we had the resources to maintain a native app for all platforms but given resources we felt we could deliver more functionality to more users via Electron, so hopefully you can bear with us while we improve.

You note about schema editing is actually one area where the current app is ahead of Realm Browser. We never had any schema editing in Realm Browser, whereas you can perform additive changes in Realm Studio (new classes, new properties). You can't do destructive changes because we focused on the schema migrations supported with synced Realms first. Adding full support of changes with local Realms is our plan.

**Comment by calumk** [comment]
@bigfish24 Great to hear some feedback on this, sorry if my original post was a bit harshly worded.

100% agree electron is the right way to go with an app like this, cross-platform is obviously the best for everyone going forward, even if we get a slightly bigger program as a result.

Could i suggest that you upload the codebase to github? I imagine it would be better to have topics like this on the specific repo, instead of on the object server repo

**Comment by bigfish24** [comment]
🙌 glad you agree with strategy and no worries on tone, I would rather have passionate feedback than none at all!

Agree it would be better to move these topics to Studio repo, but at this time we have made a decision to open source it.

**Comment by bmunkholm** [comment]
@calumk Studio is now open source, so I'll move this issue there for further comments.

**Comment by bmunkholm** [comment]
Issue moved to [realm/realm-studio #928](https://github.com/realm/realm-studio/issues/928) via [**ZenHub**](https://www.zenhub.com/)

**Comment by kraenhansen** [comment]
This feature was shipped with Realm Studio v1.20.0, please allow Studio to automatically update, test it and reopen https://github.com/realm/realm-studio/issues/928 if you have trouble using it :) Thanks again for reporting this.
