### ISSUE TITLE
ROS : 2.5.1 - Manual back up does not back up all data folders

### ISSUE THREAD

**Issue by ianbradbury-bizzibody** [realm/realm-object-server#329]
I am able to run the manual backup command with no errors.

`ros backup -f ros/data/ -t ros_backup/data`

If I look in the ros/data folder I see the following folders : `keys`, `realms`, `sync`.

If I look in the backup folder after running the backup I only see the folders : `keys` and `sync`. 

There is no `realms` folder being backed up.

## Goals

Manual back up of a live ROS server

## Expected Results

A back up folder that contains the keys, sync and realms folders.

## Actual Results

A back up folder that only contains the `keys`, `sync` and `folders`.

## Steps to Reproduce

`ros backup -f ros/data/ -t ros_backup/data`

"ros/data" is the location of my realm data.

## Version of Realm and Tooling

- Realm Object Server Version: 2.5.1
- Flavor:
  - [ ] Developer
- Server OS & Version: ? Ubuntu 16.04 64bit

**Comment by morten-krogh** [comment]
@ianbradbury-bizzibody 
Right. That is the intended behavior.
The "sync" directory contains the important server files.
The "realms" directory contains client type copies of the server realms.

If you check the content of "realms", and compare with "sync/user_data" you should find all the realms from "realms" in "sync/user_data". 

You can make an experiment yourself. Start ROS from a backup, and then check "realms" afterwards. You should see that the files have been regenerated.

This behavior is due to the fact that ROS uses the synchronization mechanism internally.

**Comment by ianbradbury-bizzibody** [comment]
Yes!

I tested, spinning up a new ROS server, copied over the back-up and voila!

Lovely Jubbly.
