### ISSUE TITLE
realm object  session out / getting closed .

### ISSUE THREAD

**Issue by AshishChagugule** [realm/realm-object-server#352]
hay hello , I need one  quick help we have integrated realm object server with android  and and ios , and it work fine .
but after some time server  getting closed and we need to reset it .   we are  not getting exact problem . will u please suggest something.  

and we are getting log from severer like 
```
[ec2-user@ip-172-31-40-160 ~]$ ros start
info: Loaded feature token capabilities=[Sync], expires=Wed Apr 19 2017 14:15:29 GMT+0000 (UTC)
info: Realm Object Server version 2.5.1 is starting
info: [sync] Realm sync server started ([realm-core-4.0.4], [realm-sync-2.1.10])
info: [sync] Directory holding persistent state: /home/ec2-user/data/sync/user_data
info: [sync] Operating mode: master_with_no_slave
info: [sync] Log level: info
info: [sync] Download log compaction is enabled
info: [sync] Max download size: 131072 bytes
info: [sync] Listening on 127.0.0.1:43055 (sync protocol version 22)
info: Realm Object Server has started and is listening on http://0.0.0.0:9080
error: [sync] Sync Connection[11]: Session[1]: Received UPLOAD message while session token had expired
```

**Comment by nirinchev** [comment]
The logs don't indicate a fatal error that would terminate the server process. What makes you think it's getting closed?

**Comment by TejaswiniChalak** [comment]
Hi @nirinchev 
Its Sagar I'm working on iOS Side along with @AshishChagugule.
This is response coming from server.
```

error: [sync] Sync Connection[8]: Session[1]: Token expired (signed_user_token='...a1mQMTPmYmmtauMoopzo+6srcg+g==').
error: [sync] Sync Connection[8]: Session[1]: Token expired (message_type='bind', signed_user_token='...a1mQMTPmYmmtauMoopzo+6srcg+g==').
```
We had used only single admin user on both side iOS and Android but I think this is happen because we had used a single user and we didnt write a code for logout the particular user. If we tried to logout from device its logout from all the devices where I logged with that admin user.

**Comment by sagarshirbhate** [comment]
Hi @nirinchev 
Its Sagar I'm working on iOS Side along with @AshishChagugule.
This is response coming from server.
```

error: [sync] Sync Connection[8]: Session[1]: Token expired (signed_user_token='...a1mQMTPmYmmtauMoopzo+6srcg+g==').
error: [sync] Sync Connection[8]: Session[1]: Token expired (message_type='bind', signed_user_token='...a1mQMTPmYmmtauMoopzo+6srcg+g==').
```
We had used only single admin user on both side iOS and Android but I think this is happen because we had used a single user and we didnt write a code for logout the particular user. If we tried to logout from device its logout from all the devices where I logged with that admin user.

**Comment by nirinchev** [comment]
The logs that you posted indicate that the SDK tried to perform some action with an expired access token. However, that token would be automatically renewed after that response and syncing should continue. Can you post the complete server log where it shows that the server process is terminated?

**Comment by astigsen** [comment]
Closing this for now as it refer to an outdated version of ROS and the user has not responded for months. Please reopen if the problem resurfaces.

**Comment by krishnasharma2018** [comment]
Hello,
We are getting this type of log on realm object server after an interval - 
Token expired (message_type='bind', signed_user_token='...72UtQ4z/WUeN+lOoW0iLG42fGAyA==').
Token expired (signed_user_token='...72UtQ4z/WUeN+lOoW0iLG42fGAyA==')

Please find attached log file from more information.
Can you please give me an idea how do we fix this issue in our android application.
Thanks in advance.
![realm_logs](https://user-images.githubusercontent.com/37453780/60276978-4659cb00-991a-11e9-9267-dddd5118e111.PNG)
