### ISSUE TITLE
ROS demands big server storage and RAM

### ISSUE THREAD

**Issue by howdyhyber** [realm/realm-object-server#357]
ROS demands big server storage and RAM.

ROS eats a lot of memory whenever i open it, which causes the ros to restart.

This is the error:

 info: [sync] HTTP Connection[20]: Connection is closed after HTTP response.
0|npm      | terminate called after throwing an instance of 'std::bad_alloc'
0|npm      |   what():  std::bad_alloc
0|npm      | Aborted (core dumped)

**Comment by tjmille2** [comment]
Same here, I think. I receive the error 
"terminate called after throwing an instance of 'realm::OutOfDiskSpace'
0|Crypto-P |   what():  posix_fallocate() failed: No space left on device"

If the @realm-admin team could provide specifications for recommended system memory and disk space, we would all be saved a lot of trouble.

**Comment by ianpward** [comment]
@Jonsapps On what version of ROS? The latest version of ROS has log compaction and a new `vacuum` tool on the server-side which will compress the Realms. I'd recommend taking a look at the latest version.

**Comment by Jonsapps** [comment]
that sounds very useful, is there any documentation on the vacuum tool?

**Comment by ianpward** [comment]
We are working on the docs but here is something to get you started
---------
We have included a small command-line tool that can be used to actually reclaim disk space (this can also improve the performance of very large Realms, due to improved cache locality). If you have Realm Object Server installed via NPM, you can find the new tool under `./node_modules/realm-sync-server/compiled/{darwin-x64|linux-x64}/bin/realm-vacuum`.

Note that vacuuming currently only works "offline", due to the way shrinking is implemented (this is another limitation we are planning to lift in the medium term). It _should_ be robust, i.e. exit safely if another process is accessing the input Realm file, but of course we must advise that you back up your server files before running `realm-vacuum`. Consult `realm-vacuum --help` for a list of options.

**Comment by astigsen** [comment]
Closing this for now as the question was answered. Please reopen if it was insufficient or the problem resurfaces.
