### ISSUE TITLE
Selective Synchronisation

### ISSUE THREAD

**Issue by ianbradbury-bizzibody** [realm/realm-object-server#40]
Can anyone tell me if selective synchronisation is on the roadmap?

i.e: Selectively synchronise rows that match a filter. 

My focus is reducing on device database size and networking requirements.

**Comment by bigfish24** [comment]
We have this on the roadmap but depending on the use case it might not be necessary. You can think of a Realm as "selective synchronization". Apps can have multiple Realms since they are very lightweight to open and close (just a URL and authorized `User`). Realm Object Server manages all the Realms for all users so what is synced to the device is always a subset on the server.

**Comment by ianbradbury-bizzibody** [comment]
@bigfish24 - Yes, I can see how there are some use cases where breaking the problem down into multiple Realms could be an answer.  

Where objects are part of a one to many relationship, using the multiple Realm route would result in record duplication.

**Comment by Montrazul** [comment]
For me this is the only reason why we currently cant use realm database for automatic synchronization. We are having Users and each User has customers related directly to the User. If every User and the related customers are synchronized to each realm client it is simply a huge memory overhead and a really big problem when it comes to data security.

We also need login and registration functionality. In our opinion it should be possible to define that only the data of the currently logged in User should get synchronized with a related client. The scenario where multiple users are using the same client device is very unlikely and even if multiple users are using the same client it should be no problem to only sync data of the currently logged in user.

We are already using realm database for our clients but for now we cant use it on the server side for synchronization exactly because of that problem. But why is that a problem? What is happening in the background? You already are working with objects. So if I have a User that User is a Realm Object. Cant you just tell the sync service to only sync the data related to exactly that Realm Object?

**Comment by astigsen** [comment]
> We are having Users and each User has customers related directly to the User.

Could each user have its own Realm containing all its customers? In that case you could selectively open only the relevant Realm(s) on the users device.

**Comment by Montrazul** [comment]
That could be a solution. Does it have any disadvantages?

**Comment by astigsen** [comment]
Only that you cannot have cross-realm relations (other than what you maintain manually, like by storing the url's of the target realms).

It would also fix your security/privacy issues as each Realm can have its own permissions detailing who has access to it.

**Comment by Montrazul** [comment]
Sounds great. I will try that!

**Comment by dennishahn** [comment]
I have another use case for that feature: We try to implement a catalog hierarchy where at the end at the tree are many blobs (< 8MB each). We want the catalog loaded by all users but the objects containing the blobs only when the user wants to. It would be great to have the partial sync option in the future for that case.

**Comment by ReDetection** [comment]
@dennishahn I would rather place an URL link to a blob instead of blob itself. Simple solution, isn't it?

**Comment by dennishahn** [comment]
Well, the intention was to avoid just that so we don't have to take care of loading the files which would be even simpler ;)

**Comment by bigfish24** [comment]
It is still our recommendation to store static blobs outside of Realm, for example S3, then just store the URL and associated metadata (such as if the file was already retrieved). For example, Realm doesn't support incremental downloads of large operations. So if a transaction that saved a blob into Realm failed to fully download, this entire transaction would be sent again. As a result, it is more efficient to download the blobs outside of Realm. We obviously want to improve this going forward, but it hasn't been the focus since object storage services like S3 are so prevalent and work well.

**Comment by samskiter** [comment]
So for context this was one of the many long list of requested features in the original sync feature request. It's an incredibly hard thing to add though and still maintain query-ability. if some part of the DB weren't synced, should queries fail or try best effort?

I seem to remember way back when there was a demo on the realm site of an app showing foursquare data, cached in Realm. I remember thinking that if you got sync, you couldn't just sync down all of Foursquares venue DB into you're phone - you were going to need some kind partial sync.

Equally if you were building, say Strava, you would want user objects connected to their runs in your database, but you wouldn't want all runs ever from strava.

If I could cache everything associated with a user, that might be the granularity needed it. If you could prove that your data query was a subset of your "caching query", realm could know it has everything it needs. Asking for "all runs done by user 4" while I have a caching query of "user 4,5 9 and 10" would definitely succeed.

Realm might even know it has the user object, but not all the runs yet because it's still syncing. So if I visited their profile I would see their basic information, but their run information would show as 'loading'. I imagine you'd have to tell realm about these logical 'lumps' in you're data.

Some queries might be impossible to reason with like this thought without some client and server-side intelligence. "All restaurants within 1 mile of my house?" for example - this isn't a natural 'field' in a DB. if you could plug into the Realm object server and help serve that caching/query request you might be able to serve it. you might even be able to logically lump it up into 'most likely' and 'all' as google maps does.

Just a hodge podge of late night thoughts there, but super excited to see where realm goes with this. This could literally redefine the way people think about APIs.

**Comment by mhergon** [comment]
Another use case:

My app will be a news service where users read their own news. Every user send a news and all the other users read/comment about this. At the beginning, database size will be under control, but after a few years the size can be considerable.

How the syncing is performed if the whole database size is 5Gb? Is there any way to sync only the 500 latest news? Or download specific news from query?

In this case, selective syncing and ability to download older news after some time or upon request would be perfect.

**Comment by neokree** [comment]
After looking for some NoSQL databases, I would suggest (instead of having a selective sync, which can be very hard to build and mantain), to be able to create some type of "Views". 
A view should be essentially a replication of a specific query, separate from the entire "global" realm but connected to it. Any created/updated/deleted object from the "global" realm will affect the views rows and maybe a user can create an object in the view that will be created in the global realm, obviously letting the developer decide how to manage it (like a Realm Function). 
I don't know if the "view" should be inserted into a realm or should be managed externally (like another new entity), maybe inserted internally could be simpler.

With this "views" concept users would be able to download only his data always, mantaining the correct sync functionality. For editing/deleting/creating permissions the view functions would do the work (letting the developer tell what you can or you can't do in the global realm). 

The only problem is actually for permissions. Some users could have a view that others don't have (I'm thinking about Basic and Pro features), so all views should have a permission tab to know what to do with new users, essentially for creating automatically the view in his realm if he belong into a permission group or not. (which require to be able for developers to create multiple user groups instead of the flag: "is an admin").

**Comment by samskiter** [comment]
@neokree Views is a great way to put it! (and I think is what I was getting at too)

So I guess I was also talking about 'subviews'. I.e from a given view, there are a set of queries, or subviews, I can get from it. Making that deterministic would seem key to partial sync, so that Realm can tell you whether the view you are seeing is incomplete (or perhaps 'not available').

**Comment by mhergon** [comment]
@neokree @samskiter maybe selective sync can be used as initial query to first download of the DB.
In my use case, I need fast starting after many years of database growing, and the ability to download "old" data if the user searchs old news.

**Comment by samskiter** [comment]
@mhergon Sorry, yes that's what I mean. Although I wouldn't limit it to just 1 query.

**Comment by Zhuinden** [comment]
Partial Sync is going to be the big feature of RMP 2.x!

Woo!

**Comment by samskiter** [comment]
🎉 Great news!

Relevant and related is Facebooks GraphQL: https://code.facebook.com/posts/1691455094417024/graphql-a-data-query-language/

**Comment by bmunkholm** [comment]
Now implemented.
