### ISSUE TITLE
iOS app's Todo sample app's link is broken. App doesn't compile either

### ISSUE THREAD

**Issue by zeeshanz** [realm/realm-object-server#423]
On this Docs page:

https://docs.realm.io/sync/getting-started-1/ios-quick-start/step-2-adding-query-based-sync

The gitHub link is broken.

I managed to find the sample app code, but it doesn't compile.

**Comment by bmunkholm** [comment]
@zeeshanz Thanks for noting this! I've fixed the docs and will check the compile error.

**Comment by ericjordanmossman** [comment]
@zeeshanz 
I was able to compile and run from a [fresh clone](https://github.com/realm/my-first-realm-app/tree/master/ios/01-query-based-sync) with the instructions in the readme.

Which package manager are you using? Could you share the error you are receiving when you build?

**Comment by zeeshanz** [comment]
Thanks @ericjordanmossman for fixing the link.

I am using CocoaPods.

I just cloned it once again, compiled fine. I must have done something wrong the first time.

However trying to log in as a new user fails in the **initializePermissions(user).** I have figured out that I can make the user Administrator, login again with this admin user so that Realm is created, and then set it back to regular user, then the app works fine for subsequent users. However this doesn't reflect in the tutorial or the Readme file.

<img width="1436" alt="Screen Shot 2019-04-02 at 5 14 52 PM" src="https://user-images.githubusercontent.com/4508321/55436812-3c1e6f80-556b-11e9-8b8a-731982b631e8.png">

**Comment by ericjordanmossman** [comment]
Ah, I see. I think I know what's happened.

The initializePermissions method requires a realm to have been created with the schema properties that are being modified.

If you're using [realm studio](https://realm.io/products/realm-studio/) then you can create a realm at the path `/default` (or delete it then recreate) and upgrade it to a reference realm. This solved the issue for me immediately.

Though, of course I'm going to make this clear in the readME and other resources. I suspect this error flew under for a bit because the realm and schema will be created beforehand as part of the tutorial walkthrough.

**Comment by zeeshanz** [comment]
I figured this out while doing my learning. But for a started its a very frustrating roadblock. The Android version of the same app worked fine though and I didn't have any problems there.

**Comment by ericjordanmossman** [comment]
Thanks for the feedback. We'll make the appropriate changes.

**Comment by bmunkholm** [comment]
@ericjordanmossman Was this fixed?

**Comment by cbush** [comment]
Built & ran from scratch. Seems to be resolved.
